-- ระบบเช็คอินของแผนก v2.0
-- รันไฟล์นี้ใน Supabase SQL Editor เพียงครั้งเดียว

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'staff' check (role in ('admin','staff')),
  created_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  booking_ref text unique,
  name text not null,
  phone text,
  table_number text not null unique check (table_number ~ '^C(1[1-9]|[2-5][0-9]|60)$'),
  seats integer not null default 8 check (seats between 1 and 20),
  college_qr_value text unique,
  checked_in_at timestamptz,
  checked_in_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.checkin_logs (
  id bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings(id) on delete cascade,
  method text not null check (method in ('qr','manual')),
  staff_id uuid not null references auth.users(id),
  staff_email text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.bookings enable row level security;
alter table public.checkin_logs enable row level security;

create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('staff','admin'));
$$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin');
$$;

-- Policies
create policy "profile own read" on public.profiles for select to authenticated using (id=auth.uid() or public.is_admin());
create policy "staff read bookings" on public.bookings for select to authenticated using (public.is_staff());
create policy "admin insert bookings" on public.bookings for insert to authenticated with check (public.is_admin());
create policy "admin update bookings" on public.bookings for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin delete bookings" on public.bookings for delete to authenticated using (public.is_admin());
create policy "staff read logs" on public.checkin_logs for select to authenticated using (public.is_staff());

-- เช็กอินผ่าน function เท่านั้น เพื่อให้ staff เช็กอินได้แต่แก้ข้อมูลอื่นไม่ได้
create or replace function public.check_in_booking(p_booking_id uuid, p_method text)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_email text;
  v_table text;
begin
  if not public.is_staff() then raise exception 'not authorized'; end if;
  if p_method not in ('qr','manual') then raise exception 'invalid method'; end if;

  select table_number into v_table from public.bookings where id=p_booking_id for update;
  if v_table is null then raise exception 'booking not found'; end if;
  if v_table !~ '^C(1[1-9]|[2-5][0-9]|60)$' then raise exception 'table outside department range'; end if;
  if exists(select 1 from public.bookings where id=p_booking_id and checked_in_at is not null) then raise exception 'already checked in'; end if;

  select email into v_email from auth.users where id=auth.uid();
  update public.bookings set checked_in_at=now(), checked_in_by=auth.uid(), updated_at=now() where id=p_booking_id;
  insert into public.checkin_logs(booking_id,method,staff_id,staff_email) values(p_booking_id,p_method,auth.uid(),v_email);
end;
$$;

grant execute on function public.check_in_booking(uuid,text) to authenticated;

-- นำเข้า snapshot รายการ "ชำระแล้ว" ใหม่ทั้งชุด
-- เก็บสถานะ checked-in เดิมไว้ถ้า booking_ref เดิมยังมีอยู่
create or replace function public.replace_paid_bookings(p_rows jsonb)
returns void language plpgsql security definer set search_path = public as $$
declare r jsonb;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;

  create temporary table tmp_import(
    booking_ref text, name text, phone text, table_number text, seats integer, college_qr_value text
  ) on commit drop;

  for r in select * from jsonb_array_elements(p_rows) loop
    if coalesce(r->>'table_number','') !~ '^C(1[1-9]|[2-5][0-9]|60)$' then
      raise exception 'invalid table: %', r->>'table_number';
    end if;
    insert into tmp_import values(
      nullif(r->>'booking_ref',''), r->>'name', nullif(r->>'phone',''), r->>'table_number', coalesce((r->>'seats')::int,8), nullif(r->>'college_qr_value','')
    );
  end loop;

  if exists(select table_number from tmp_import group by table_number having count(*)>1) then raise exception 'duplicate table in import'; end if;

  -- ลบเฉพาะรายการที่ยังไม่เช็กอินและไม่มีใน snapshot ใหม่
  delete from public.bookings b
  where b.checked_in_at is null and not exists(
    select 1 from tmp_import t where (t.booking_ref is not null and t.booking_ref=b.booking_ref) or t.table_number=b.table_number
  );

  insert into public.bookings(booking_ref,name,phone,table_number,seats,college_qr_value)
  select booking_ref,name,phone,table_number,seats,college_qr_value from tmp_import
  on conflict (table_number) do update set
    booking_ref=excluded.booking_ref, name=excluded.name, phone=excluded.phone, seats=excluded.seats,
    college_qr_value=excluded.college_qr_value, updated_at=now();
end;
$$;

grant execute on function public.replace_paid_bookings(jsonb) to authenticated;

-- Realtime
alter publication supabase_realtime add table public.bookings;

-- หลังสร้างผู้ใช้ใน Authentication > Users แล้ว ให้กำหนดสิทธิ์ด้วยคำสั่งตัวอย่างด้านล่าง
-- insert into public.profiles(id,role) values ('USER_UUID_HERE','admin');
-- insert into public.profiles(id,role) values ('USER_UUID_HERE','staff');
